services:
  - type: web
    name: receipt-scanner-api
    env: docker
    rootDir: .
    dockerfilePath: ./YOLO_Trainer/Dockerfile
    envVars:
      - key: ENV
        value: production
      - key: OLLAMA_HOST
        sync: false  # This allows overriding through dashboard
      - key: API_TIMEOUT
        value: 30
      - key: ENABLE_CACHE
        value: true
      - key: PORT
        value: 8000
    healthCheckPath: /check
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 80
    startCommand: python YOLO_Trainer/detect_api.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 