services:
  - type: web
    name: receipt-scanner-api
    env: docker
    rootDir: .
    dockerfilePath: YOLO_Trainer/Dockerfile
    envVars:
      - key: ENV
        value: production
      - key: OLLAMA_HOST
        value: https://5959-161-142-237-109.ngrok-free.app
      - key: API_TIMEOUT
        value: 30
      - key: ENABLE_CACHE
        value: true
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 