services:
  - type: web
    name: receipt-scanner-api
    env: docker
    rootDir: .
    dockerfilePath: ./YOLO_Trainer/Dockerfile
    envVars:
      - key: ENV
        value: production
      - key: OLLAMA_HOST
        value: http://fcca-161-142-237-109.ngrok-free.app
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: DEBUG
      - key: CONNECT_TIMEOUT
        value: 5.0
      - key: READ_TIMEOUT
        value: 30.0
      - key: WRITE_TIMEOUT
        value: 30.0
      - key: POOL_TIMEOUT
        value: 30.0
      - key: ENABLE_CACHE
        value: "true"
      - key: API_TIMEOUT
        value: 60.0
    healthCheckPath: /check
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 80
    startCommand: python YOLO_Trainer/detect_api.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 