services:
  - type: web
    name: receipt-scanner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn detect_api:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OLLAMA_HOST
        value: https://ollama.ai
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 